- pyblazing/api.py
> [REVIEW] Delete the workaround/hack: FreeMemory

- pyblazing/__init__.py
- pyblazing/api.py
- pyblazing/apiv2/context.py
- pyblazing/apiv2/datasource.py
Now create_table function accept more parameters, for instance:
`
bc.create_table('proof', ["/../datasets/proof.csv"], names=proofColNames, delimiter=',', lineterminator='\n', skiprows=0, skipinitialspace=False, delim_whitespace=True, skip_blank_lines=False, quotechar='"', quoting=1, doublequote=False, decimal='.', nrows=3,na_filter=0, keep_default_na=0, dayfirst=False, thousands=None, comment=None, true_values=None, false_values=["False", "false"], na_values=["NA"])`
> Adding parameter in create table and validate them

- ci/cpu/pyblazing/conda-build.sh
- ci/cpu/upload_anaconda.sh
- conda/recipes/pyBlazing/meta.yaml
Fix label to main to anaconda cloud.
Fix name of package
> WIP: Fix Label to anaconda packages

- scripts/build-all-conda.sh
- scripts/build-all.sh
Adding param clean_build to clean the repo and pull new code.
> feat(conda) updating script build-all.sh

- conda/recipes/blazingsql-dev/build.sh
- conda/recipes/blazingsql-dev/meta.yaml
- conda/recipes/pyBlazing/meta.yaml
- scripts/build-all-conda.sh
- scripts/build-all.sh
Removing param branch, adding param build's type and terminating process is one of them fail
> Fixing some bugs on build-all.sh and adding param build's type and version from git tag

- ci/cpu/pyblazing/conda-build.sh
- conda-build.sh
- conda-upload-docker.sh
- conda-upload.sh
- conda/recipes/pyBlazing/meta.yaml
> [REVIEW] gpuci

- pyblazing/api.py
- pyblazing/apiv2/context.py
This PR is to make it so that services can all start at the same time and they use a pinging mechanism to know they are all available to use. It also introduces a shutdown command to more elegantly shut down all services
WORTH NOTING (potentially controversial, but I find really useful for devs and users) :
- This exposes two new functions to BlazingContext()
- ready() : it returns true if all services return a ping. Can take an optional parameter `wait` to have the function call wait untill all services are up. This will be very handy for testing framework, and potentially other customer workflows, error recovery and more     
- shutdown()
> [REVIEW] Feature/robust service start

- README.md
This PR just update the README and remove the instructions to create a /blazingsql folder and stuff
> [REVIEW] Use in-memory H2 config so we get ride of using a directory

- pyblazing/api.py
https://github.com/BlazingDB/pyBlazing/issues/91
> resolves https://github.com/BlazingDB/pyBlazing/issues/91

- pyblazing/apiv2/context.py
The schema of the `bsql_logs` table is:
node_id              int32     this is the node id  (ie.  0, 1, 2, 3)
type                object       Log message type (INFO (performance logging), TRACE (other query execution messages), WARNING, ERROR)
query_id             int32     Random ID number
step                 int16       Query execution step. Should correlate with Relational Algebra step number
substep              int16    Query execution substep. This is incremented when step is incremented and also incremented at each communication 
info                object        Description of the step
duration           float32     Duration (for performance logging)
extra1              object       Description of extra info1  about the step  (i,e, num rows)
data1                int32 …
> [TESTING] python API for queryable logs

- engine/bsql_engine/io/io.pyx
> [TESTING] fix/hdfs-driver

- engine/src/CalciteExpressionParsing.cpp
- engine/src/Interpreter/interpreter_ops.cuh
> [REVIEW] Fixes incorrect result using case statement with an int and a float

- engine/CMakeLists.txt
- engine/src/execution_graph/logic_controllers/LogicPrimitives.cpp
- engine/src/execution_graph/logic_controllers/LogicPrimitives.h
- engine/src/execution_graph/logic_controllers/LogicalFilter.cpp
- engine/src/execution_graph/logic_controllers/LogicalFilter.h
Makes first example of new function signatures using applyBooleanFilter as example
> Feature/execution graph 0.12

- engine/src/execution_graph/logic_controllers/LogicalFilter.cpp
- engine/src/execution_graph/logic_controllers/LogicalFilter.h
Adds ability to create hash partitions and to run joins. resolves #196 resolves #203
> added join function

- comms/include/blazingdb/manager/Context.h
- comms/include/blazingdb/transport/Address.h
- comms/include/blazingdb/transport/Node.h
- comms/src/blazingdb/manager/Context.cc
- comms/src/blazingdb/transport/Address.cc
- comms/src/blazingdb/transport/Node.cc
- engine/src/communication/CommunicationData.cpp
- engine/src/communication/CommunicationData.h
- engine/src/distribution/primitives.cpp
- engine/src/distribution/primitives.h
- engine/src/gdf_wrapper/gdf_wrapper.cuh
- engine/src/utilities/CommonOperations.cpp
- engine/src/utilities/CommonOperations.h
This PR changes Context, Address and Node to no longer use `std::shared_ptr`
Additionally implements various distribution primities
> engine communication migration part 1 on many

- pyblazing/pyblazing/apiv2/context.py
> [Testing] Fixing table input as pyarrow

- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/include/engine/engine.h
- engine/src/cython/engine.cpp
> [REVIEW] feature/cython-cudf012

- algebra/blazingdb-calcite-core/src/main/java/com/blazingdb/calcite/catalog/domain/CatalogColumnDataType.java
- algebra/blazingdb-calcite-core/src/main/java/com/blazingdb/calcite/schema/BlazingTable.java
- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/src/cython/engine.cpp
- engine/src/io/data_parser/CSVParser.cpp
- pyblazing/pyblazing/apiv2/context.py
This PR fixes:
- calcite column types defs
- some csv reader logic
- all the c++/cython/python code related to the sync between cudf datatypes with calcite catalog schema
See https://github.com/BlazingDB/blazingsql/issues/288
> [REVIEW] Fix calcite integration with cudf0.12 symbols

- engine/CMakeLists.txt
- engine/src/utilities/DebuggingUtils.cpp
- engine/src/utilities/DebuggingUtils.h
Utility for printing a BlazingTableView.
Usage:
#include "utilities/DebuggingUtils.h"
...
ral::utilities::print_blazing_table_view(blz_table_view);
> [REVIEW] Feature/print blazing table

- engine/src/io/data_parser/CSVParser.cpp
Fix https://github.com/BlazingDB/blazingsql/issues/297
> [REVIEW] Fix issues with wildcard for CSV files

- engine/src/io/data_parser/OrcParser.cpp
- engine/src/io/data_parser/OrcParser.h
Fix https://github.com/BlazingDB/blazingsql/issues/301
> [REVIEW] Fix ORC sql reader for new cudf0.12 code

- engine/src/execution_graph/logic_controllers/LogicalFilter.cpp
This fixes the join operator, but will need to be revisited when an issue on CUDF is actually fixed https://github.com/rapidsai/cudf/issues/3974
> [REVIEW] Fix/join operator cudf0.12

- engine/bsql_engine/io/io.pyx
- engine/src/Interpreter/interpreter_cpp.cu
- engine/src/io/data_parser/GDFParser.cpp
Fix https://github.com/BlazingDB/blazingsql/issues/304
> [REVIEW] Fix create table and run query from GDF (cudf 0.12 port)

- engine/src/CalciteExpressionParsing.cpp
- engine/src/CalciteExpressionParsing.h
- engine/src/Interpreter/interpreter_cpp.cu
- engine/src/Interpreter/interpreter_cpp.h
- engine/src/Interpreter/interpreter_ops.cuh
- engine/src/execution_graph/logic_controllers/LogicalFilter.cpp
- engine/src/execution_graph/logic_controllers/LogicalFilter.h
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/execution_graph/logic_controllers/LogicalProject.h
- engine/src/operators/GroupBy.cpp
- engine/src/parser/expression_tree.hpp
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- engine/src/skip_data/utils.cpp
- engine/tests/new-tests/process_project.cu
Migrates LIKE, CONCAT, SUBSTR, CAST TO VARCHAR string functions
> [REVIEW] String functions migrations

- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
Fix https://github.com/BlazingDB/blazingsql/issues/314
> [REVIEW] Fix all where tests

- engine/bsql_engine/io/io.pyx
- engine/src/operators/OrderBy.cpp
> [REVIEW] fix/limit-cudf012

- engine/src/CalciteExpressionParsing.cpp
Fix https://github.com/BlazingDB/blazingsql/issues/321
> [REVIEW] Fix floor parse

- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
Fixes this kind of queries: """select c_custkey + 1, c_custkey + 1 from customer"""  and other queries related to setting aliases.
> [REVIEW] Fix/column names

- engine/src/execution_graph/logic_controllers/LogicPrimitives.cpp
- engine/src/execution_graph/logic_controllers/LogicPrimitives.h
- engine/src/io/DataLoader.cpp
Fix https://github.com/BlazingDB/blazingsql/issues/368
> [REVIEW] Fix loading of empty tables keeping the schema (io/dataloader)

- pyblazing/pyblazing/apiv2/context.py
Fix https://github.com/BlazingDB/blazingsql/issues/397
> [REVIEW] Port RMM allocation args to branch-0.13

- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/operators/GroupBy.cpp
- engine/src/operators/OrderBy.cpp
This PR needs https://github.com/rapidsai/cudf/pull/4158
This PR fix https://github.com/BlazingDB/blazingsql/issues/359
> [REVIEW] Fix limit logic

- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/include/engine/engine.h
- engine/src/cython/engine.cpp
- engine/src/execution_graph/logic_controllers/LogicalFilter.cpp
- engine/src/execution_graph/logic_controllers/LogicalFilter.h
- pyblazing/pyblazing/apiv2/context.py
> [WIP] Partition function

- engine/src/io/data_parser/ParquetParser.cpp
Fixes #463 
Leaving the code as it was before because the issue has already been fixed on cudf.
> [REVIEW] Uncommenting reading of rowgroups

- pyblazing/pyblazing/apiv2/context.py
> [REVIEW] implemented relative paths

- engine/src/Interpreter/interpreter_ops.cuh
- engine/tests/new-tests/interops_tests.cu
> [REVIEW] Returning nan instead of inf when division is by zero

- engine/src/io/Schema.cpp
- engine/src/io/data_parser/ParquetParser.cpp
- engine/src/io/data_parser/metadata/parquet_metadata.cpp
Do not merge this, @williamBlazing will take some change from here in order to create the final part of the patches
> [WIP] patch parse_schema, parse and read_metadata when the parquet file is empty

- comms/include/blazingdb/transport/api.h
- engine/CMakeLists.txt
- engine/src/communication/messages/GPUComponentMessage.h
- engine/src/execution_graph/logic_controllers/BlazingHostTable.cpp
- engine/src/execution_graph/logic_controllers/BlazingHostTable.h
- engine/src/execution_graph/logic_controllers/LogicPrimitives.h
- engine/tests/cache_machine/CMakeLists.txt
> [REVIEW] fixing BlazingMutableThread

- CHANGELOG.md
- algebra/blazingdb-calcite-application/src/main/java/com/blazingdb/calcite/application/RelationalAlgebraGenerator.java
- algebra/blazingdb-calcite-application/src/main/java/com/blazingdb/calcite/application/SqlValidationException.java
- changelog
- pyblazing/pyblazing/apiv2/context.py
A bit rudimentary but our previous version relied on pattern matching which was crashing.
> [Testing] start showing errors when query doesnt parse correctly

- CHANGELOG.md
- changelog
- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/include/io/io.h
- engine/src/CalciteExpressionParsing.cpp
- engine/src/cython/io.cpp
- engine/src/execution_graph/logic_controllers/LogicalFilter.cpp
- engine/src/io/DataLoader.cpp
- engine/src/io/data_parser/ArrowParser.cpp
- engine/src/io/data_parser/ArrowParser.h
- engine/src/io/data_parser/CSVParser.cpp
- engine/src/io/data_parser/CSVParser.h
- engine/src/io/data_parser/DataParser.h
- engine/src/io/data_parser/GDFParser.cpp
- engine/src/io/data_parser/GDFParser.h
- engine/src/io/data_parser/JSONParser.cpp
- engine/src/io/data_parser/JSONParser.h
- engine/src/io/data_parser/OrcParser.cpp
- engine/src/io/data_parser/OrcParser.h
- engine/src/io/data_parser/ParquetParser.cpp
- engine/src/io/data_parser/ParquetParser.h
- engine/src/io/data_provider/DataProvider.h
- engine/src/io/data_provider/DummyProvider.h
- engine/src/io/data_provider/UriDataProvider.cpp
- engine/src/io/data_provider/UriDataProvider.h
- pyblazing/pyblazing/apiv2/context.py
- pyblazing/pyblazing/apiv2/hive.py
> [TESTING] create_table with user defined partitions

- io/src/FileSystem/private/S3FileSystem_p.cpp
Fix https://github.com/BlazingDB/blazingsql/issues/206
> [TESTING] Fix wildcard for S3

- engine/src/cython/engine.cpp
> [TESTING] Feature editing duplicate column names

- engine/src/distribution/primitives.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
This PR is for minimizing empty tables, but not allowing them to be added to caches or being sent in shuffles
> [TESTING] Feature/minimizing empty tables

- engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.h
- engine/src/execution_graph/logic_controllers/BatchOrderByProcessing.h
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
- engine/src/operators/OrderBy.cpp
> [TESTING] Fix/ready to execute

- pyblazing/pyblazing/apiv2/context.py
Needed for workers with no partitions of a dask dataframe
> [WIP] Compute schema for dask dataframe

- conda/recipes/blazingsql/meta.yaml
- engine/CMakeLists.txt
- engine/tests/CMakeLists.txt
- engine/tests/cache_machine/CMakeLists.txt
cc @felipeblazing @williamBlazing @jeanp413 @mario21ic
> [REVIEW] use sdplog provided by conda

- CHANGELOG.md
- engine/tests/new-tests/CMakeLists.txt
- engine/tests/new-tests/apply_filter.cu
- engine/tests/new-tests/filter_tests.cu
- engine/tests/new-tests/interops_tests.cu
- engine/tests/transport/CMakeLists.txt
- engine/tests/transport/gpu-batch-tcp-server-client-test.cc
> [REVIEW] Fix unit tests

- CHANGELOG.md
- comms/include/blazingdb/network/TCPSocket.h
- comms/include/blazingdb/transport/Client.h
- comms/include/blazingdb/transport/Server.h
- comms/include/blazingdb/transport/io/reader_writer.h
- comms/src/blazingdb/transport/Client.cc
- comms/src/blazingdb/transport/Server.cc
- comms/src/blazingdb/transport/io/fd_reader_writer.cpp
- comms/src/blazingdb/transport/io/reader_writer.cpp
- engine/src/communication/messages/GPUComponentMessage.cpp
- engine/src/parser/expression_tree.cpp
Reverts BlazingDB/blazingsql#727
> Revert "[REVIEW] Use cudaMallocHost in PinnedBuffer"

- CHANGELOG.md
- engine/src/CalciteExpressionParsing.cpp
- engine/src/CalciteExpressionParsing.h
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.h
- engine/src/execution_graph/logic_controllers/BatchUnionProcessing.h
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
- engine/src/utilities/CommonOperations.cpp
- engine/src/utilities/CommonOperations.h
- tests/BlazingSQLTest/EndToEndTests/innerJoinsTest.py
- tests/BlazingSQLTest/EndToEndTests/unionTest.py
> [REVIEW] type normalizing for UNION ALL

- CHANGELOG.md
- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/include/engine/engine.h
- engine/src/CalciteInterpreter.cpp
- engine/src/CalciteInterpreter.h
- engine/src/cython/engine.cpp
- engine/src/execution_graph/logic_controllers/PhysicalPlanGenerator.h
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- pyblazing/pyblazing/apiv2/context.py
- tests/BlazingSQLTest/EndToEndTests/unionTest.py
> [REVIEW] each table scan now has its own data loader

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
> [REVIEW] Fix when the algebra plan was provided using one-line as logical plan

- CHANGELOG.md
- README.md
- build.sh
- conda/recipes/blazingsql/meta.yaml
- engine/src/io/data_parser/ArgsUtil.cpp
- pyblazing/pyblazing/apiv2/context.py
Related to https://github.com/BlazingDB/blazingsql/issues/800
> [REVIEW] Fix conda build

- .gitignore
- CHANGELOG.md
- build.sh
- conda-build-docker.sh
Related to https://github.com/BlazingDB/blazingsql/issues/827
> [WIP] Fix gpuci issues and improve tooling to debug gpuci related issues

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.h
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.h
- engine/src/execution_graph/logic_controllers/BatchOrderByProcessing.h
- engine/src/execution_graph/logic_controllers/BatchProcessing.h
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
This implemens unordered pull from cache whenever it can and also implements functions for downgrading caches to be used for another feature
> [WIP] unordered pull from cache

- CHANGELOG.md
- build.sh
Added check for CUDF_HOME to allow build to use an existing prebuilt cudf source tree.
> [ENH] Added check for CUDF_HOME to allow build to use an existing prebuilt cudf source tree

- CHANGELOG.md
- engine/src/io/data_parser/ParquetParser.cpp
> [WIP] Fix row_groups issue in ParquetParser.cpp

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
> stopped using dask for scheduling single gpu tasks and jsut round robin

- CHANGELOG.md
- engine/src/Interpreter/interpreter_ops.cuh
- engine/src/distribution/primitives.cpp
We were previously using an include from the test side of things which was ill advised. This is the proper include file with the apis we need
> Fix include from cudf

- CHANGELOG.md
- build.sh
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.h
- engine/src/execution_graph/logic_controllers/PhysicalPlanGenerator.h
fixed issue caused by replacing join load_set with concatenating cache and issue in distributing CROSS_JOIN
> [REVIEW] fixed issue caused by replacing join load_set with concatenating cache

- CHANGELOG.md
- docs/conf.py
- docs/index.rst
requires that you install doxygen apt-get also have to install exhale along with sphinx using pip
> added using exhale to be able to generate docs,

- CHANGELOG.md
- engine/src/io/data_parser/CSVParser.cpp
- engine/src/io/data_parser/CSVParser.h
- engine/src/io/data_parser/JSONParser.cpp
- engine/src/io/data_parser/JSONParser.h
- engine/src/io/data_parser/OrcParser.cpp
- engine/src/io/data_parser/OrcParser.h
- engine/src/io/data_parser/ParquetParser.cpp
- engine/src/io/data_parser/ParquetParser.h
> [REVIEW] Update all readers to use arrow_io_source

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/CacheMachine.h
Just adding doc comments to CacheMachine.h
> [WIP] added doxygen comments to CacheMachine.h

- CHANGELOG.md
- engine/src/parser/expression_utils.cpp
- engine/tests/parser/CMakeLists.txt
- engine/tests/parser/expression_utils_test.cpp
> [REVIEW] Fix for the count(*) special case

- CHANGELOG.md
- build.sh
- engine/CMakeLists.txt
- engine/tests/CMakeLists.txt
- io/CMakeLists.txt
- io/src/Config/BlazingContext.cpp
- io/src/FileSystem/private/FileSystemFactory.cpp
- io/tests/CMakeLists.txt
> [REVIEW] Make AWS and GCS optional

- CHANGELOG.md
- engine/src/CalciteInterpreter.cpp
- engine/src/execution_graph/logic_controllers/taskflow/graph.cpp
- engine/src/execution_graph/logic_controllers/taskflow/graph.h
- engine/src/utilities/ctpl_stl.h
> [REVIEW] Adding max kernel num threads pool

- CHANGELOG.md
- engine/src/parser/expression_tree.cpp
This is a fix implemented by Jens Glasser in another PR
> [REVIEW] fixed random segault issue in parser

- CHANGELOG.md
- engine/bsql_engine/io/cio.pxd
- engine/include/engine/engine.h
- engine/include/engine/initialize.h
- engine/include/io/io.h
- engine/src/cython/engine.cpp
- engine/src/cython/initialize.cpp
- engine/src/cython/io.cpp
- engine/src/error.hpp
> [WIP] Adding extern C for include files

- CHANGELOG.md
- engine/src/operators/OrderBy.cpp
> [REVIEW] Fix/typo sample

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
This PR add two functions:
* list_tables() : returns a list with all the created tables
* describe_table(table_name) : returns the column names and column types as a dictionary.
And a doc about these functions.
Closes #954
> [REVIEW] Add list_tables() and describe_table() functions

- CHANGELOG.md
- build.sh
- engine/src/io/data_parser/ArgsUtil.cpp
- engine/src/io/data_parser/OrcParser.cpp
Fixed minor issue due to cudf orc api. Also changed when cmake is called for cudf. It is now only run with `./build.sh update`.
> [WIP] fixed issue due to cudf orc api change

- CHANGELOG.md
- README.md
- ci/gpu/build.sh
- conda/recipes/blazingsql/meta.yaml
- engine/src/io/data_parser/ArgsUtil.cpp
- engine/src/io/data_parser/ArgsUtil.h
- engine/src/io/data_parser/JSONParser.cpp
- engine/src/io/data_parser/JSONParser.h
- engine/src/io/data_parser/ParquetParser.cpp
- io/src/FileSystem/private/GoogleCloudStorageReadableFile.cpp
- io/src/FileSystem/private/S3ReadableFile.cpp
- powerpc/build.sh
This PR also  fix issues related to new parquet API in cudf.
> [REVIEW] fixing arrow compilation

- CHANGELOG.md
- engine/src/cython/engine.cpp
- engine/src/cython/io.cpp
- engine/src/io/data_parser/ArgsUtil.cpp
- engine/src/io/data_parser/ArgsUtil.h
- engine/src/io/data_parser/CSVParser.cpp
- engine/src/io/data_parser/CSVParser.h
- engine/src/io/data_parser/JSONParser.cpp
- engine/src/io/data_parser/JSONParser.h
- engine/src/io/data_parser/OrcParser.cpp
- engine/src/io/data_parser/OrcParser.h
- tests/BlazingSQLTest/Runner/runTest.py
> [REVIEW] reworked how arguments are handled in the parsers

- CHANGELOG.md
- build.sh
- comms/tests/CMakeLists.txt
- engine/CMakeLists.txt
> [REVIEW] Removing cudf dependency as a thirdparty code

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
> [REIVEW] fixed issue with concat all in concatenating cache

- CHANGELOG.md
- engine/src/io/data_provider/DataProvider.h
- engine/src/io/data_provider/UriDataProvider.cpp
- engine/tests/CMakeLists.txt
- engine/tests/provider/CMakeLists.txt
- engine/tests/provider/provider_test.cpp
> [REVIEW] Fix for empty folders

- CHANGELOG.md
- ci/cpu/upload_anaconda.sh
cc @dillon-cullinan as this requires backend Jenkins changes to be coordinated as well
> [REVIEW] Upload conda packages to both blazingsql and rapidsai conda channels

- CHANGELOG.md
- engine/CMakeLists.txt
- engine/tests/CMakeLists.txt
Fixes the issue caused by cudf PR https://github.com/rapidsai/cudf/pull/6134
Not sure if its the "cleanest" fix.
> [REVIEW] fixed issue caused by cudf changing from one .so file to multiple

- CHANGELOG.md
- io/src/FileSystem/private/GoogleCloudStorage_p.cpp
This PR improves the error returned by the Google API showing more information about the origin of the problem when validating any bucket.
> [REVIEW] Improves the error message when validating the GCP bucket

- CHANGELOG.md
- engine/src/cython/initialize.cpp
- pyblazing/pyblazing/apiv2/context.py
> [REVIEW] Logs configurable to have max size and be rotated

- CHANGELOG.md
- engine/src/io/data_provider/UriDataProvider.cpp
Deal with the unexpected crash on #857
> [REVIEW] Throwing an error message when trying to open a directory with wildcards

- CHANGELOG.md
- ci/gpu/test.sh
- engine/tests/provider/provider_test.cpp
- io/src/FileSystem/private/LocalFileSystem_p.cpp
> [REVIEW] Adding additional provider test

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/PhysicalPlanGenerator.h
> [REVIEW] Improving message error for invalid or unsupported expressions

- CHANGELOG.md
- engine/src/bmr/BlazingMemoryResource.h
- pyblazing/pyblazing/apiv2/context.py
This PR brings to branch-0.17 the hotfix changes from #1099 and also adds a fix when validating the local_files param
> [REVIEW] Fix config_options and logging for branch 0.17

- CHANGELOG.md
- tests/BlazingSQLTest/EndToEndTests/allE2ETest.py
- tests/BlazingSQLTest/EndToEndTests/dayOfWeekTest.py
- tests/BlazingSQLTest/Runner/runTest.py
- tests/README.md
> [REVIEW] Add dayOfWeekTest.py

- CHANGELOG.md
- ci/gpu/build.sh
This line should fix some of the SSL errors that have been occurring in GPU builds.
> Ignore SSL errors for gpu builds

- CHANGELOG.md
- engine/src/cython/initialize.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
> [REVIEW] Don't log timeout in output/input caches

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/comms.py
- pyblazing/pyblazing/apiv2/context.py
> [REVIEW] Remove unnecesary prints (cluster and logging info)

- CHANGELOG.md
- engine/src/cython/io.cpp
> [REVIEW] Create table in distributed mode crash with a InferFolderPartitionMetadata Error 

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/taskflow/graph.cpp
- engine/src/utilities/ctpl_stl.h
> [REVIEW] Fix graph thread pool hang when exception is thrown

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- tests/BlazingSQLTest/EndToEndTests/allE2ETest.py
- tests/BlazingSQLTest/EndToEndTests/stringCaseTest.py
- tests/BlazingSQLTest/Runner/runTest.py
Enables use of UPPER or LOWER in a query and adds end to end tests for both operators
Passes ./test.sh locally.
This closes #1134 and closes #1135
> [REVIEW] Implement UPPER and LOWER operators and tests

- CHANGELOG.md
- engine/tests/new-tests/interops_tests.cpp
> [WIP] Add unit test day of week

- CHANGELOG.md
- pyblazing/setup.py
> [REVIEW] Change hardcoded version from setup.py

- CHANGELOG.md
- engine/src/operators/GroupBy.cpp
- io/src/Util/StringUtil.cpp
- io/tests/CMakeLists.txt
- io/tests/Util/CMakeLists.txt
- io/tests/Util/StringUtilTest.cpp
- tests/BlazingSQLTest/EndToEndTests/allE2ETest.py
- tests/BlazingSQLTest/EndToEndTests/groupByTest.py
> [REVIEW] Fixing string replacing

- README.md
This PR remove labels from installation instructions
> feat(readme) updating instructions

- CHANGELOG.md
- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/include/engine/engine.h
- engine/src/CalciteInterpreter.cpp
- engine/src/CalciteInterpreter.h
- engine/src/cython/engine.cpp
- engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchProcessing.h
- engine/src/execution_graph/logic_controllers/taskflow/graph.cpp
- engine/src/execution_graph/logic_controllers/taskflow/graph.h
- engine/src/execution_graph/logic_controllers/taskflow/kernel.h
- pyblazing/pyblazing/apiv2/context.py
This PR introduces the concept of starting the execution of the graph. Checking to see if its done and then retrieving the result. This allows for multiple concurrent queries to execute. It also allows for the ability to check the status of an executing query and provide a progress bar or something like that
Resolved #1274
> [REVIEW] Multiple concurrent query support

- CHANGELOG.md
- engine/src/cython/initialize.cpp
- pyblazing/pyblazing/apiv2/context.py
> [REVIEW] Infer PROTOCOL when Dask client is passed

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
> [REVIEW] Adding again trailing slash removed by os.path.abspath

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- tests/BlazingSQLTest/EndToEndTests/stringCaseTest.py
This PR is based on #1260. Thanks @derekmorr for the great work implementing this feature. This PR closes #1177
> [REVIEW] Add support for INITCAP

- CHANGELOG.md
- engine/bsql_engine/io/io.pyx
- engine/src/io/data_parser/metadata/orc_metadata.cpp
- engine/src/operators/OrderBy.cpp
- engine/src/parser/expression_utils.cpp
> [REVIEW] Fixing uninitialized variable in orc metadata and handling their exceptions properly

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- tests/BlazingSQLTest/EndToEndTests/caseTest.py
> [REVIEW] Handling properly the nulls in Case's with strings

- CHANGELOG.md
- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/src/execution_graph/logic_controllers/CacheData.cpp
- engine/src/execution_graph/logic_controllers/CacheData.h
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/taskflow/executor.cpp
- engine/tests/communication/message_send_receive.cpp
…eData instead and other related changes
> [REVIEW] removed GPUCacheDataMetadata class

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchOrderByProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchUnionProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchWindowFunctionProcessing.cpp
- engine/src/execution_graph/logic_controllers/taskflow/executor.cpp
- engine/src/parser/expression_utils.cpp
Source: https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR61-CPP.+Catch+exceptions+by+lvalue+reference
> [REVIEW] Capturing error messages due to exceptions properly

- CHANGELOG.md
- engine/src/bmr/BufferProvider.cpp
- engine/src/bmr/BufferProvider.h
https://github.com/BlazingDB/blazingsql/issues/1317
> [REVIEW] Delete allocated host chunks

- CHANGELOG.md
- engine/src/bmr/BufferProvider.cpp
- engine/src/bmr/BufferProvider.h
- engine/src/communication/CommunicationInterface/messageReceiver.cpp
- engine/tests/allocation_pool/allocation_pool.cpp
Make buffer providers singleton to avoid cuda issues with pinned memory de-allocation
> [WIP] Avoid cuda issues when free pinned memory

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
> [WIP] give useful message when file extension is not recognized

- conda-build-docker.sh
This PR is for testing gpuCI upload packages.
> [REVIEW] conda: updating docker script

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp
- engine/src/operators/GroupBy.cpp
- engine/src/operators/GroupBy.h
- tests/BlazingSQLTest/EndToEndTests/coalesceTest.py
> [REVIEW] Recompute `columns_to_hash` in DistributeAggregationKernel

- CHANGELOG.md
- engine/src/cython/engine.cpp
- engine/src/io/data_parser/ParquetParser.cpp
- pyblazing/pyblazing/apiv2/context.py
> [REVIEW] Fix empty row_group_ids for parquet

- CHANGELOG.md
- engine/src/parser/expression_utils.cpp
- tests/BlazingSQLTest/EndToEndTests/caseTest.py
> [REVIEW] Fix issue when CAST a literal

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.cpp
- tests/BlazingSQLTest/EndToEndTests/allE2ETest.py
- tests/BlazingSQLTest/EndToEndTests/nonEquiJoinsTest.py
This PR fixes Issue #1383
Note that this PR first tried to actually fix the issue https://github.com/BlazingDB/blazingsql/pull/1390
But the algorithm does not work in all cases, so we had to disable the support we thought we had
> [REVIEW] Disabled support for outer joins with inequalities

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- engine/tests/parser/expression_utils_test.cpp
- io/src/Util/StringUtil.cpp
- tests/BlazingSQLTest/EndToEndTests/unaryOpsTest.py
> [REVIEW] Fix support for minus unary operation

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchWindowFunctionProcessing.cpp
- engine/src/operators/GroupBy.cpp
- engine/src/operators/GroupBy.h
- tests/BlazingSQLTest/EndToEndTests/windowFunctionTest.py
This PR closes #1409
This PR closes #1410  
This PR closes #1411
> [REVIEW] Fix for tests 13,23, 26, 27 of window function

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.cpp
- tests/BlazingSQLTest/EndToEndTests/coalesceTest.py
This PR closes #1404 
This PR closes #1405
> [WIP] Fix full join when both tables contains nulls

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- engine/tests/parser/expression_utils_test.cpp
- tests/BlazingSQLTest/EndToEndTests/concatTest.py
> [REVIEW] Support for CONCAT alias operator

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
- engine/src/execution_graph/logic_controllers/taskflow/graph.cpp
- engine/src/execution_graph/logic_controllers/taskflow/kernel.cpp
- engine/src/execution_graph/logic_controllers/taskflow/kernel.h
> [REVIEW] Improve getting estimated output num rows

- CHANGELOG.md
- README.md
- ci/gpu/build.sh
- conda/recipes/blazingsql/meta.yaml
- dependencies.sh
Changes:
1. Update dependencies script to support stable and nightly versions
2. Update gpu build script
3. Set dependency nlohmann_json to version 3.9.1
> [REVIEW] Update installation dependencies

- CHANGELOG.md
- README.md
This PR updates the README.md and CHANGELOG.md for the 0.19 release
> v0.19.0 Pre-release

- CHANGELOG.md
- Dockerfile
This PR fixes some conflicts in order to generate the release v0.19 docker images
> [REVIEW] Fixing some conflicts in Dockerfile

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.cpp
- tests/BlazingSQLTest/EndToEndTests/allE2ETest.py
- tests/BlazingSQLTest/EndToEndTests/coalesceTest.py
- tests/BlazingSQLTest/EndToEndTests/countDistinctTest.py
- tests/BlazingSQLTest/EndToEndTests/groupByTest.py
- tests/BlazingSQLTest/EndToEndTests/predicatesWithNullsTest.py
- tests/BlazingSQLTest/EndToEndTests/rightOuterJoinsTest.py
- tests/BlazingSQLTest/Runner/runTest.py
This PR closes #1391.  In order to this PR be successful is needed this PR BlazingDB/blazingsql-testing-files#28 will be merged first.
> [REVIEW] Support for right outer join

- CHANGELOG.md
- conda/recipes/blazingsql/meta.yaml
- dependencies.sh
Changes:
1. Update spdlog package to support version 1.8.5
> [REVIEW] update spdlog version

- CHANGELOG.md
- engine/tests/provider/provider_test.cpp
> [WIP] Enables provider unit_tests

- engine/src/bmr/BufferProvider.cpp
- engine/src/bmr/BufferProvider.h
- engine/tests/allocation_pool/allocation_pool.cpp
fixed error where the ucx mem handle was getting freed twice because it was part of the pool instead of being part of the allocation
> [REVIEW] UCX double free bug fix

- CHANGELOG.md
- engine/src/io/data_parser/metadata/orc_metadata.cpp
- engine/src/io/data_parser/metadata/orc_metadata.h
This PR fix the compilation for `branch-21.06 `due to new API for orc statistics stuff
> [REVIEW] Fix orc statistic building

- CHANGELOG.md
- conda/recipes/blazingsql/meta.yaml
- dependencies.sh
Changes:
1. Update spdlog package to version 1.8.5
> [WIP] Pinning spdlog to version 1.8.5

- CHANGELOG.md
- engine/src/blazing_table/BlazingHostTable.cpp
- engine/src/communication/CommunicationInterface/serializer.cpp
- engine/src/communication/CommunicationInterface/serializer.hpp
- engine/src/communication/messages/GPUComponentMessage.cpp
- engine/src/io/data_parser/metadata/common_metadata.cpp
- engine/src/io/data_parser/sql/sqlcommon.h
- engine/src/utilities/CommonOperations.h
- engine/tests/utilities/MemoryConsumer.cu
This fixes the build due to changes in rmm from this PR https://github.com/rapidsai/rmm/pull/775/files
> VDE-285 Fix/update rmm device buffer

- README.md
This PR was made to launch gpuCI in order to generate Conda packages.
> [REVIEW] readme: adding an empty line

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
> [WIP] Cast decimal from orc to float64
