BlazingDB/blazingsql

- pyblazing/api.py
Right now when a script ends, and a context goes out of scope, it can terminate the processes and therefore closing connection throws and error and freeing results also throws an error. This PR just silences those errors.
> [REVIEW] silence errors happening when a script ends

- pyblazing/api.py
When you set the dtype as boolean.
dtypes=['str', 'int32', 'boolean]
bc.create_table('table_name', 'path/file.csv', dtype=dtypes)
Now when a dtype is boolean then it's recognized.
> [Review] Adding boolean type to recognize in dtypes

- pyblazing/api.py
Example:
ral1 returns empty result
ral2 returns empty result
This fix will concat both empty results and thus generate correctly the final gdf (with correct metadata such as columns names and so on)
Before this fix the final gdf is None and produce invalid result in the case mentioned above
> [REVIEW] When all rals return empty results we still want to concat

- ci/cpu/build-dev.sh
- ci/cpu/build.sh
This fix is to avoid the python package blazingsql as a conda channel
> [REVIEW] set default channel blazingsql/label/main

- pyblazing/pyblazing/apiv2/context.py
`cudf.set_allocator` calls `rmm.reinitialize`. It's just a wrapper that guarantees the function is called exactly once.
> [REVIEW] Use cudf.set_allocator to initialize GPU memory allocator

- algebra/conda/recipes/bsql-algebra/build.sh
- comms/conda/recipes/bsql-comms/build.sh
- conda/recipes/blazingsql/build.sh
- engine/CMakeLists.txt
- engine/conda/recipes/bsql-engine/build.sh
- engine/conda/recipes/libbsql-engine/build.sh
- engine/setup.py
- io/conda/recipes/bsql-io/build.sh
- pyblazing/conda/recipes/pyblazing/build.sh
These changes add bsql-rapids-thirdparty dependency in order to build with Cudf 0.12
Also, there are some lines to detect if someone script fails
> [REVIEW] Adding rapids-thirdparty

- engine/src/execution_graph/logic_controllers/LogicalFilter.cpp
- engine/src/execution_graph/logic_controllers/LogicalFilter.h
The new hash_partition function has the following API 
```std::pair<std::unique_ptr<experimental::table>, std::vector<size_type>>
hash_partition(table_view const& input,
std::vector<size_type> const& columns_to_hash,
int num_partitions,
rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());```
Which means we want to use split with the output, which in turn means that the way the allocations need to be managed changed a bit, which resulted in refactoring a bit of the code
> [REVIEW] updated code due to cudf changed API for hash_partition function

- engine/src/io/DataLoader.cpp
Fix cases when we want to read a single file using many dask workers and we are not selecting any index (e.g. select * ...)
> [REVIEW] Fix create empty tables: when there are no selected indices read all the schema

- engine/src/io/data_parser/ParquetParser.cpp
- engine/src/utilities/CommonOperations.cpp
This is a temporary workaround that fixes #463
> [REVIEW] Parquet workaround for reading consecutive rowgroups

- CHANGELOG.md
- engine/src/io/data_parser/ArgsUtil.cpp
Before this we were defaulting to header=-1 and not handling header=None. This now handles both those situations in the same way that read_csv does.
> [Testing] made us have same behaviour as cudf for reading csv (header)

- comms/src/blazingdb/transport/Address.cc
Before we were copying metadata and this is incorrect because metadata has a static array inside of it. This properly handles the copying of the metadata. We should in the future modify metadat so that it uses std::string instead
> Fix error on copy construction address

- engine/src/distribution/primitives.cpp
- engine/src/distribution/primitives.h
- engine/src/execution_graph/logic_controllers/BatchOrderByProcessing.h
- engine/src/execution_graph/logic_controllers/PhysicalPlanGenerator.h
- engine/src/operators/OrderBy.cpp
- engine/src/operators/OrderBy.h
THIS PR makes it so that the number of partitions is does for an order by is based on a hardcoded max number of bytes per partition, currently set to 400MB. It also has a maximum number of 8 partitions per node, because the number of output caches is still hardcoded. 
From here we want to make the max number of bytes per partition be a configurable parameter and the number of output caches be able to be dynamically set
> [TESTING] Changed number of partitions for order by to be more dynamic

- ci/cpu/upload_anaconda.sh
- conda-build-docker.sh
This fix is to be able to build a Conda package from a local docker container which is emulating gpuCI environment.
Example:
```
$ ./conda-build-docker.sh 10.0 3.7 <conda_token> beta mario21ic-nightly
```
> feat(gpuci) updating script to build locally

- engine/src/cython/initialize.cpp
- pyblazing/pyblazing/apiv2/context.py
implements logging into the initialization which includes product info and initialization info:
2020-05-15 09:33:02.944|0|debug||||INITIALIZING RAL. RAL ID: 0, RAL Host: 127.0.0.1:18022, Network 
Interface: lo, , Is Not Single Node, CUDA_VISIBLE_DEVICES is set to: 0,1, |||||
2020-05-15 09:33:02.944|0|debug||||Product Details: BLAZINGSQL_GIT_BRANCH: fix/missing_nodes_in_das
k_cudf_table; BLAZINGSQL_GIT_COMMIT_HASH: 32805f63f526b59920c8cc045ce1a98bde062ba6; BLAZINGSQL_GIT_
DESCRIBE_NUMBER: 429; BLAZINGSQL_GIT_DESCRIBE_TAG: v0.14.0; CMAKE_CUDA_COMPILER: /usr/local/cuda/bi
n/nvcc; CMAKE_CUDA_FLAGS: -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -
gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 --expt-extended-lambda …
> [REVIEW] added logging into the initialization

- CHANGELOG.md
- algebra/blazingdb-calcite-core/pom.xml
certain queries were having errors like if you tried to do between or a x > a and x < b type of query. it was because of a class missing because of missing guava dependencies
> [REVIEW] added guava to pom.xml

- CHANGELOG.md
- engine/bsql_engine/io/cio.pxd
- engine/bsql_engine/io/io.pyx
- engine/include/engine/engine.h
- engine/include/io/io.h
- engine/src/CalciteInterpreter.cpp
- engine/src/CalciteInterpreter.h
- engine/src/cython/engine.cpp
- engine/src/execution_graph/logic_controllers/BatchProcessing.h
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
- pyblazing/pyblazing/apiv2/context.py
Reverts BlazingDB/blazingsql#601
That PR has some good functions related to string length and concatenation that we want to keep, but the way we were handling the multi partition outputs is not quite right on the dask/python side
> Revert "[REVIEW] Fix/vector result tables"

- CHANGELOG.md
- engine/src/Interpreter/interpreter_cpp.cu
- engine/src/Interpreter/interpreter_cpp.h
- engine/src/Interpreter/interpreter_ops.cuh
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- engine/tests/new-tests/interops_tests.cpp
- engine/tests/new-tests/process_project.cpp
users are now able to use the RAND() function in queries both  as an output and as part of an expression. Right now there is a bug where if you do something along the lines of 
In addition users can now also run queries like 
```
select rand(), sin(3.14) * 2 from orders where o_orderkey < 300
```
> [Review] unary ops on literals, added rand() function to interops and parser

- CHANGELOG.md
- engine/src/error.hpp
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.cpp
- engine/src/execution_graph/logic_controllers/BatchJoinProcessing.h
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
- engine/src/execution_graph/logic_controllers/LogicPrimitives.cpp
- engine/src/execution_graph/logic_controllers/LogicPrimitives.h
- engine/src/execution_graph/logic_controllers/PhysicalPlanGenerator.h
- engine/src/execution_graph/logic_controllers/taskflow/graph.h
- engine/src/execution_graph/logic_controllers/taskflow/kpair.h
- pyblazing/pyblazing/apiv2/context.py
This PR brings over the CacheMachine code from the UCX branch.
It also improves ConcatenatingCache::pullFromCache to not decache until necessary
It also replaces PartwiseJoin::load_set with a concatenating cache on each input of PartwiseJoin
It also gets rid of flow control batch count, so that flow control feature only now works using bytes count. (with default parameters that was not being used anyways). This was removed to reduce code complexity.
> [REVIEW] concatenating cache improvement

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
This PR does two things to make starting a Dask-powered BlazingContext require less work:
1.  Use `dask.distributed.default_client` to see if there is a default Dask client lying around
2.  Iterate through local network interfaces to find the interface being used to connect to the Dask scheduler
So now if you have some Dask things running
```python
cluster = dask_cuda.LocalCUDACluster()
client = dask.distributed.Client(cluster)
```
Then you should be able to create a `BlazingContext` without parameters
```python
bc = BlazingContext()
```
You all may prefer to be very explicit here.  I think that the network interface code is useful regardless.  However I could imagine an argument for wanting users to opt-in to Dask, even if they have a Dask client around.  
I haven't tested this at all
> [REVIEW] Use nicer defaults for dask_client and network_interface

- CHANGELOG.md
- engine/src/cython/initialize.cpp
- pyblazing/pyblazing/apiv2/context.py
This PR uses the param `LOGGING_LEVEL` for set the level of logs we want. So the new name for the flush_level is `LOGGING_FLUSH_LEVEL`
Closes #953
> [REVIEW] Set log_level when using LOGGING_LEVEL param

- CHANGELOG.md
- engine/bsql_engine/io/cio.pxd
- engine/src/distribution/primitives.cpp
- engine/src/execution_graph/logic_controllers/taskflow/graph.cpp
- engine/src/utilities/ctpl_stl.h
Throwing manually an exception on the  `run()` method from `BindableTableScan`.
```
BlazingContext ready
[16:05:36.925] [error] 256896318|1|1|In BindableTableScan kernel batch for BindableTableScan(table=[[main, nation]], filters=[[<($1, 3)]], projects=[[0, 2]], aliases=[[n_nationkey, $f1]]). What: Throwing a runtime exception inside BindableTableScan|||||
[16:05:36.926] [error] 256896318|0|0|In execute_plan. What: An exception occurred when run() method was called|||||
An exception occurred when run() method was called[16:05:36.926] [error] 256896318|0|0|In runQuery. What: An exception occurred when run() method was called|||||
>>>>>>>>  [RunQuery Error] An exception occurred when run() method was called
Empty DataFrame
Columns: []
Index: []
Series([], dtype: float64)
```
> [REVIEW] Handle exceptions from pool_threads

- CHANGELOG.md
- comms/include/blazingdb/transport/io/reader_writer.h
- comms/src/blazingdb/transport/io/reader_writer.cpp
This PR fix the issue when calling twice to the `std::unique_lock<std::mutex> lock` in the `PinnedBufferProvider`.
> [REVIEW] Remove lock inside grow() method from PinnedBufferProvider

- CHANGELOG.md
- engine/bsql_engine/io/io.pyx
Fixes #99
Example:
```python
customerColNames = ["c_custkey", "c_name", "c_address", "c_nationkey", "c_phone", "c_acctbal", "c_mktsegment", "c_comment"]
customerColTypes = ["int32", "str", "str", "int32", "str", "float64", "str", "str"]
bc.create_table('orders', ["compressed_file.gz"], delimiter='|', dtype=customerColTypes, names=customerColNames, file_format="csv", compression='gzip')
```
> [REVIEW] Allow to create tables from compressed files

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/comms.py
- pyblazing/pyblazing/apiv2/context.py
- pyblazing/pyblazing/apiv2/filesystem.py
- pyblazing/pyblazing/test/test_comms.py
We can use `ddf.shuffle(on=[colnames])` instead of bc.partition, so we should just deprecate it.
This closes #1011  and #1123
> deprecating bc.partition

- CHANGELOG.md
- ci/cpu/upload_anaconda.sh
- conda/recipes/blazingsql/meta.yaml
This PR allows us to install BlazingSQL without Cuda labels. So this could be the command:
```
$ conda install -c blazingsql-nightly -c rapidsai-nightly -c nvidia -c conda-forge -c defaults blazingsql python=3.8  cudatoolkit=10.2
```
Also this PR fixes #1167
> [REVIEW] Removing cuda labels to install due cudatoolkit version

- CHANGELOG.md
- algebra/blazingdb-calcite-application/src/main/java/com/blazingdb/calcite/application/RelationalAlgebraGenerator.java
This PR:
- Enables MySQL-specific SQL operators, which makes several useful string operators potentially available (REVERSE, LEFT, RIGHT, etc.). Currently only Standard SQL and Oracle SQL are available.
I've confirmed that this change does allow Calcite to use these operators. Passes `./test.sh` locally.
This closes #1178 
```python
from blazingsql import BlazingContext
import pandas as pd
bc = BlazingContext()​
​
df = pd.DataFrame({
"a": ["one", "two"],
"b": [1, 2],
})
​
bc.create_table("df", df)
​
query = """
SELECT
a,
REVERSE(a)
FROM df
"""
print(bc.explain(query))
LogicalProject(a=[$0], EXPR$1=[REVERSE($0)])
BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[a, EXPR$1]])
```
> [REVIEW] Enable MySQL-specific SQL operators in addition to Standard and Oracle

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/parser/expression_utils.cpp
- engine/src/parser/expression_utils.hpp
- tests/BlazingSQLTest/EndToEndTests/stringTests.py
This PR:
This closes #1173 
```python
from pyspark.sql import SparkSession
from blazingsql import BlazingContext
import pandas as pd
df = pd.DataFrame({
"a": ["Felipe", "William", "Rodrigo"],
"b": [10, 9, 8],
})
bc.create_table("df", df)
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
query = """
SELECT
a,
REVERSE(a) as reversed_a
FROM df
"""
spark.sql(query).show()
print(bc.sql(query))
+-------+----------+
|      a|reversed_a|
+-------+----------+
| Felipe|    epileF|
|William|   mailliW|
|Rodrigo|   ogirdoR|
+-------+----------+
a reversed_a
0   Felipe     epileF
1  William    mailliW
2  Rodrigo    ogirdoR
```
> [REVIEW] Implement string REVERSE

- CHANGELOG.md
- engine/src/parser/expression_tree.cpp
- engine/tests/new-tests/process_project.cpp
This PR closes #1041 
By default Calcite uses `int32` for literal values (as long as it does not exceed the limit of an `int32`) 
For each of these queries 
```
query = "select cast(32 as INT) as col_a from df"
query = "select cast(32 as INTEGER) as col_a from df"  
query = "select 32 as col_a from df"  
```
The Relational Algebra returns:
```
DEBUG: com.blazingdb.calcite.application.RelationalAlgebraGenerator - non optimized
LogicalProject(col_a=[32])
LogicalTableScan(table=[[main, df]])
DEBUG: com.blazingdb.calcite.application.RelationalAlgebraGenerator - optimized
LogicalProject(col_a=[32])
BindableTableScan(table=[[main, df]], projects=[[]], aliases=[[col_a]])
```
Some of other SQL engines (as `pyspark.sql`) returns also a `int32`, at least you explicitly apply  a `CAST`
> [REVIEW] Calcite uses literal as int32 if  not explicit CAST was provided

- CHANGELOG.md
- engine/src/communication/CommunicationInterface/messageReceiver.cpp
- engine/src/communication/CommunicationInterface/messageSender.cpp
- engine/src/cython/engine.cpp
- engine/src/cython/initialize.cpp
- engine/src/execution_graph/logic_controllers/BatchProcessing.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
- engine/src/execution_graph/logic_controllers/taskflow/distributing_kernel.cpp
- engine/src/execution_graph/logic_controllers/taskflow/executor.cpp
- engine/tests/communication/message_send_receive.cpp
- pyblazing/pyblazing/apiv2/comms.py
- pyblazing/pyblazing/apiv2/context.py
- tests/BlazingSQLTest/EndToEndTests/configOptionsTest.py
This PR has a couple improvements:
Adds unique ids to comms messages so that they can be more uniquely identified, and also adds begin and end phases.
Fixed issues in initialization of logs when multiple BlazingContexts are getting created at the same time.
Also gets rid of `TABLE_SCAN_KERNEL_NUM_THREADS` which is no longer used
> [REVIEW] Fixes to initialization and adding unique ids to comms

- CHANGELOG.md
- engine/CMakeLists.txt
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/tests/CMakeLists.txt
Fix because of https://github.com/rapidsai/cudf/pull/7107.
Temporaly fix due to https://github.com/rapidsai/cudf/issues/7500 related to https://github.com/rapidsai/cudf/pull/7415
> [REVIEW] Fix build due to libcudf sublibs changes

- powerpc/build.sh
- pyblazing/pyblazing/apiv2/context.py
Update to a more recent version of the IBM Java SDK version 11 (the previous version was not available for download anymore and the build script failed).
Allow users to directly specify the path to `libjvm.so` in the `JAVA_HOME` environment variable, since the internal directory structure of the SDK has changed. Maybe it would make sense to make this the new documented default way, and eliminate the convoluted logic here
https://github.com/BlazingDB/blazingsql/blob/20f2fa94411c6a8b3557b8cc18b72d9220a2b07f/pyblazing/pyblazing/apiv2/context.py#L75-L95
> Fix JDK install for Power9

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/LogicalProject.cpp
- engine/src/io/data_parser/metadata/orc_metadata.cpp
This PR also undoes the workaround for replace function since the issue was fixed in cudf https://github.com/rapidsai/cudf/pull/7502.
> [REVIEW] Fixing build due to some refactor in cudf

- CHANGELOG.md
- engine/src/io/data_parser/metadata/orc_metadata.cpp
This PR is a temporary work around for #1385 but it will skip when dtype is `DECIMAL`. If the issue is not due to a `DECIMAL` dtype then it will throw a more descriptive message about the dtype that is causing the issue,
> [WIP] Skip getting orc metadata for decimal type

- CHANGELOG.md
- engine/src/execution_graph/logic_controllers/CacheMachine.cpp
- engine/src/execution_graph/logic_controllers/CacheMachine.h
- engine/src/execution_graph/logic_controllers/PhysicalPlanGenerator.h
- engine/src/execution_graph/logic_controllers/WaitingQueue.h
- engine/src/execution_graph/logic_controllers/taskflow/graph.h
- engine/src/execution_graph/logic_controllers/taskflow/kpair.h
- pyblazing/pyblazing/apiv2/context.py
Resolves #1414 
This PR introduces a time out to ConcatenatingCacheMachine, so that it will either wait to accumulate a certain number of bytes, or for a timeout (which is configurable) or for the CacheMachine to `finish()`.
> [REVIEW] Feature/concat cache machine timeout

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
Raising exceptions on C-side graph errors (either execute or generate) on the Python side. This is a temp fix before the full Python code refactor will take place.
> Throw python exceptions

- CHANGELOG.md
- pyblazing/pyblazing/apiv2/context.py
- tests/BlazingSQLTest/EndToEndTests/booleanTest.py
Adding a warning `WARNING: Window Functions are currently an experimental feature and not fully supported or tested` for any time a user runs a window function. This will be removed when we are more confident in the feature. Right now we know it has a lot of holes and bugs
> Added Warning to Window Functions

- CHANGELOG.md
- algebra/blazingdb-calcite-core/src/main/java/com/blazingdb/calcite/catalog/domain/CatalogColumnDataType.java
- algebra/blazingdb-calcite-core/src/main/java/com/blazingdb/calcite/schema/BlazingTable.java
- pyblazing/pyblazing/apiv2/context.py
- pyblazing/pyblazing/apiv2/hive.py
This PR closes #1493
Notes:
* This PR does not implement support for Decimal/Fixed Point at all, so it's not expected you can do sql operations for this type of data.
* This PR specifically solves the issue reported. 
* For now it is possible to create tables that contains columns with `decimal` type using `cudf.DataFrame`, `dask_cudf.DataFrame` , `parquet` and `orc` as inputs,
> [REVIEW] Fix Decimal/Fixed Point issue

- CHANGELOG.md
- build.sh
- conda/recipes/blazingsql/meta.yaml
- dependencies.sh
This PR updates the `ucx-py` versions used by Blazing. `ucx-py` will not be switching to calendar versioning like the rest of RAPIDS, so their versions must be updated accordingly (similar to https://github.com/rapidsai/cuml/pull/3911 and https://github.com/rapidsai/cugraph/pull/1634).
For now I've hard-coded the values here to help unblock some RAPIDS builds, but I will update Blazing accordingly if we set up any automation here.
> Update ucx-py versions

- CHANGELOG.md
- ci/cpu/build.sh
- conda/recipes/blazingsql/meta.yaml
- engine/src/io/data_parser/ArgsUtil.cpp
- engine/src/io/data_parser/OrcParser.cpp
- engine/src/parser/expression_utils.cpp
- engine/tests/parser/expression_utils_test.cpp
This PR adds `CC`, `CXX`, and `CUDAHOSTCXX` entries to the `build.script_env` section of the `conda` recipe, so that those environment variables get passed through the `build.sh` script and ultimately to CMake. This enables CMake to use the correct versions of `gcc` and `g++` when compiling.
Additionally, it includes some fixes for the upstream cudf changes in https://github.com/rapidsai/cudf/pull/8142
> [REVIEW] Fix `CC`/`CXX` variables in CI

- CHANGELOG.md
- ci/checks/style.sh
- dependencies.sh
- engine/tests/parser/parquet_metadata_test.cpp
- tests/BlazingSQLTest/EndToEndTests/oldScripts/hiveFileTest.py
This PR contains fixes for issues of building, cc @romulo-auccapuclla 
This PR also contains fixes for new arrow API 4.0.1 (due to `cudf-nightly`)
This PR contains a fix due to https://github.com/rapidsai/cudf/pull/8692  (related to the conda env name).
Note:  Something that worries me is that the `HiveFileTest` lately crashes randomly with a `std::bad_alloc `(query 01 CSV, that was commented out).
> [REVIEW] fix latest cudf dependencies

- CHANGELOG.md
- engine/setup.py
Changes:
1. Add compile argument thrust-ignore-cub-version-check in order to fix build issue
> [REVIEW] Add argument thrust-ignore-cub-version-check

- CHANGELOG.md
- conda/recipes/blazingsql/meta.yaml
There is a conda solver conflict due to BlazingSQL using a higher version of `spdlog` than the rest of RAPIDS. This PR simply pins `spdlog` to the same as [`librmm`](https://github.com/rapidsai/rmm/blob/branch-21.08/conda/recipes/librmm/meta.yaml#L38).
> Pin spdlog to match RAPIDS

- CHANGELOG.md
- conda/recipes/blazingsql/meta.yaml
- dependencies.sh
Starting with `google-cloud-cpp>=1.30`, it requires `libgcc-ng>=9.4.0` which is not compatible with RAPIDS. RAPIDS requires `libgcc-ng==9.3.0`.
I've testing this build and install with RAPIDS `21.08` locally and it works with this change.
> Restrict Google cloud cpp version
